---
name: bosh-powerdns-release

releases:
- name: bosh-powerdns-release
  version: latest

stemcells:
- alias: ubuntu
  os: ubuntu-xenial
  version: latest

instance_groups:
- name: pdns
  instances: 1
  azs: [ z1 ]
  vm_type: default
  persistent_disk_type: default
  stemcell: ubuntu
  networks:
  - name: service
    static_ips: [10.245.0.101]
  jobs:
  - name: pdns
    release: bosh-powerdns-release
  properties:
    powerdns:
      postgresql:
        host: 10.245.0.6
        password: Dz4hkHMKDq8iOl8Afg8TsJmtcjTipF

update:
  canaries: 1
  max_in_flight: 10
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
